### ISSUE TITLE
Actions = none breaks functionality

### ISSUE THREAD

**Issue by jbreuer95** [jrief/django-admin-sortable2#100]
when actions = none the sorting bar gets really long and sorting only works once.
when you try to move an item a second time it uses the old id.

**Comment by jrief** [comment]
what do you mean by "when actions = none the sorting bar gets really long and sorting only works once."?

did you try to order the items using the management command?

**Comment by jbreuer95** [comment]
When you add the option: actions = None to an adminview you disable the select box. 
When the select box is disabled you get this effect:
![screen shot 2016-04-29 at 12 42 25](https://cloud.githubusercontent.com/assets/5371337/14914127/e6a95b30-0e07-11e6-8bb0-6896d9409ec1.png)

**Comment by jrief** [comment]
ah, interesting!
Is this django-1.8 or 1.9. In 1.9 the css for admin changed a lot.

**Comment by jbreuer95** [comment]
1.9.

Also changing items doesn't work right with the select box disabled.
Example:
When i change item one to position 3 it works fine.
But if i try to change the item again from position 3 to 5 it fails.
This is because the JS thinks the item still has position 1 and not 3.
Im not getting any JS errors but something is failing i suppose.

For now ill just enable the checkboxes, great plugin!

**Comment by jrief** [comment]
Fixed in 0.6.4
