### ISSUE TITLE
Allow override SortableAdminMixin.get_max_order based on request 

### ISSUE THREAD

**Issue by joseph2002** [jrief/django-admin-sortable2#101]
Could the get_max_order method take the request and obj(optional) as an argument, e.g. get_max_order(self, request, obj=None), so that it is possible to do some subset ordering based on foreignkey, with combination of get_extra_model_filters

**Comment by jrief** [comment]
Does this mean that you want to override ``get_max_order`` in your ModelAdmin class?

Hmm, I always saw this as kind of internal method, but if this helps in your use case, well why not?
You want to create a pull request?

**Comment by jrief** [comment]
I just added this feature request.
