### ISSUE TITLE
How to save changes in list view with SortableAdminMixin

### ISSUE THREAD

**Issue by gbcgit** [jrief/django-admin-sortable2#103]
Nice project.  Well done!  Just one issue for me.

The ModelAdmin / List View for a model is displayed, I see the order column, and I can drag and drop the ordering of the rows.  That works nicely.  When done, if I refresh the page, it reverts back.  That makes sense, since the in the Admin the main use case is to save with a save button.  However, there isn't a save button on my page.  I can't find any explanation on how to save changes in the list view in the docs.  Please help.

**Comment by gbcgit** [comment]
Update.  I had the order field in my list_display.  This seems to have been the problem.  I removed it, and now a ajax call is updating the order.  So, nevermind.

**Comment by goutomroy** [comment]
When trying to add new column to a existing table with data then you have to run following :+1: 
manage.py reorder my_app.models.MyModel

check here:
http://django-admin-sortable2.readthedocs.io/en/latest/usage.html
