### ISSUE TITLE
Ordering not saved if not specified in admin.TabularInline.fields?

### ISSUE THREAD

**Issue by wasabigeek** [jrief/django-admin-sortable2#110]
In admin.TabularInline.fields, if I leave out the ordering field, changes in the ordering are not saved. Is this expected?

e.g.
models.py
```
class Photo(models.Model):
    name = models.CharField(max_length=255)
    order = models.PositiveIntegerField(default=0, blank=False, null=False)


    class Meta(object):
        ordering = ('order',)

```
admin.py
```
class PhotoInline(SortableInlineAdminMixin, admin.TabularInline):
    model = Photo
    extra = 0
    fields = ('name',)
    readonly_fields = ('admin_img','photo')


class VenueAdmin(ImportExportActionModelAdmin):
    list_display=('name')
    inlines = [
        PhotoInline,
    ]
    pass
```

After changing the order in the Admin interface and saving, the order is not saved. I have to change `fields = ('name',)` to `fields = ('name', 'order')`.

If it's expected behaviour, propose to state this in the documentation.

**Comment by jrief** [comment]
Yes ``order`` is rendered as a hidden field and accessed by the JavaScript part of this app. It always must be the first ordering field.

**Comment by wasabigeek** [comment]
Ok thanks. I added proposed changes to docs https://github.com/jrief/django-admin-sortable2/pull/112
