### ISSUE TITLE
Cannot sort same model in List and Inline views?

### ISSUE THREAD

**Issue by wasabigeek** [jrief/django-admin-sortable2#111]
If I have a model that is sortable in both the List and Inline view, after sorting it the Inline view, I may have issues sorting in the List view.

From what I can tell, sorting Inline will rank the objects within that scope only e.g.
- 100 objects in List View, initial migration will make this ordered from 1-100
- 10 objects in Inline View, on save it will order from 1-10, which could be the same as an existing object in the other 90 objects
- subsequent attempts to reorder in List View cause MultipleObjectsReturned errors since the order clashes

**Comment by jrief** [comment]
Did you apply an additional filter when rendering the ListView?
