### ISSUE TITLE
SortableInlineAdminMixin does not work with parler TranslatableTabularInline

### ISSUE THREAD

**Issue by racitup** [jrief/django-admin-sortable2#118]
I have tried creating an inline admin using:
`class ProductFAQAdminInline(SortableInlineAdminMixin, TranslatableTabularInline, admin.TabularInline):`.
If I omit the `admin.TabularInline`, adminsortable2 gives an error stating I need to subclass.

I suspect the library is not written to support this but haven't checked in the code yet.

The javascript works and the item can be dragged, but on save and refresh, the item order has not changed.

**Comment by jrief** [comment]
So, what you say ist that you tried with?
```
class ProductFAQAdminInline(SortableInlineAdminMixin, TranslatableTabularInline):
    ...
```

**Comment by racitup** [comment]
Hi,
Yes, when I try that and I get:

> File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/adminsortable2/admin.py", line 375, in template
>     raise ImproperlyConfigured('Class {0}.{1} must also derive from admin.TabularInline or admin.StackedInline'.format(self.__module__, self.__class__))
> django.core.exceptions.ImproperlyConfigured: Class myproducts.admin.faq.<class 'myproducts.admin.faq.ProductFAQAdminInline'> must also derive from admin.TabularInline or admin.StackedInline

I'm using:
django-admin-sortable2==0.6.4
django-parler==1.6.4

**Comment by racitup** [comment]
Okay, I got this working with the following addition to `admin.py`
```
    @property
    def template(self):
        if isinstance(self, admin.StackedInline):
            return 'adminsortable2/stacked.html'
        elif isinstance(self, admin.TabularInline):
            return 'adminsortable2/tabular.html'
        else:
            try:
                from parler.admin import TranslatableInlineModelAdmin, TranslatableStackedInline, TranslatableTabularInline
                if isinstance(self, TranslatableInlineModelAdmin):
                    if self.inline_tabs:
                        print("Warning: adminsortable2 is incompatible with parler inline_tabs")
                        return super().template
                    elif isinstance(self, TranslatableStackedInline):
                        return 'adminsortable2/stacked.html'
                    elif isinstance(self, TranslatableTabularInline):
                        return 'adminsortable2/tabular.html'
                    raise ImportError
            except ImportError:
                raise ImproperlyConfigured('Class {0}.{1} must also derive from admin.TabularInline/admin.StackedInline/parler.admin.TranslatableInlineModelAdmin'.format(self.__module__, self.__class__))
```

I also had to include the `ordering` field in the inline for it to save the order value to the db:
```
class ProductFAQAdminInline(SortableInlineAdminMixin, TranslatableTabularInline):
    ...
    fieldsets = (
        (_("Translated FAQ"),       {'fields': ('question', 'answer', 'question_order')}),
    )
    ...
```
Thanks for all the hard work!

**Comment by racitup** [comment]
I have forked and committed my changes. Should I submit a pull request? I'm pretty new to this...

**Comment by jrief** [comment]
Yes, I have seen your branch.
Anyway, IMHO django-parler should offer mixin classes to convert a Stacked/TabularInline into a translatable entities. This is the Pythonic way to add functionality to 3rd party classes. Someone shall create a PR for it in  django-parler.

**Comment by racitup** [comment]
For reference: [pull request](https://github.com/jrief/django-admin-sortable2/pull/119)

**Comment by racitup** [comment]
It appears that inheriting both the django and parler admin classes works:
`class ProductFAQAdminInline(SortableInlineAdminMixin, TranslatableTabularInline, admin.TabularInline):`
django-parler v1.7
django-admin-sortable2 v0.6.11
