### ISSUE TITLE
Add to doc: ordering field must be in viewable fields for inlines

### ISSUE THREAD

**Issue by mitchelljkotler** [jrief/django-admin-sortable2#125]
For my inline, I have `fields` defined to choose which fields to show.  I did not add my ordering field to this tuple, and I could drag and drop my inlines, but the ordering would not persist with no indication  of what went wrong (my screen looked just like the screenshots.)  I eventually realized I needed to add the ordering field to the `fields` tuple, but it would be nice to make a note of that in the documentation.

**Comment by jrief** [comment]
please check if the docs are good enough now.

**Comment by mitchelljkotler** [comment]
I don't see any changes in the 0231a6a that address this issue

**Comment by jrief** [comment]
usage.rst line 159

**Comment by mitchelljkotler** [comment]
` +.. note:: Remember to also set the list ``ordering`` in the ``Meta`` class of ``MySubModel``. `

That is not what this bug was referring too , I was referring too the need to add the ordering field to the `fields` list for `InlineModelAdmin` class
