### ISSUE TITLE
Sortable and StackedInline

### ISSUE THREAD

**Issue by sylvainlb** [jrief/django-admin-sortable2#129]
When I use ```class QuestionInline(SortableInlineAdminMixin, admin.TabularInline):``` I get what I expect, sortable lines. But when I replace `TabularInline` with `StackedInline` : ```class QuestionInline(SortableInlineAdminMixin, admin.StackedInline):``` The lines don't get sortable anymore.
I'm using Django 1.9 with a very standard application.
Does StackedInline require specific configuration?
What did I miss?

Thanks for your work!

**Comment by jrief** [comment]
StackedInline does not require a specific configuration, but I admit that the draggable area is not easily visible. Go to the top of a StackedInline element and try to drag it.
This only works for existing inlines, not the newly created ones.

**Comment by sylvainlb** [comment]
Indeed, It works, I just needed to find where to click. Thanks!
