### ISSUE TITLE
django-admin-sortable2 breaks django-cleanup

### ISSUE THREAD

**Issue by kennell** [jrief/django-admin-sortable2#132]
Please see https://github.com/un1t/django-cleanup/issues/34 for details

**Comment by ppython** [comment]
@kennell , do you mind trying out my PR #135 ?

**Comment by kennell** [comment]
Sorry for the long delay, i can confirm this fixes the issue. Thank you, i appreciate you taking the time to fix this.

**Comment by ppython** [comment]
Well, thanks goes especially towards @vinnyrose :)
