### ISSUE TITLE
[bug] dragging gives newposition - 1

### ISSUE THREAD

**Issue by freskimo** [jrief/django-admin-sortable2#143]
When dragging an item e.g. 1 to 3 and then refresh the page the item gets order 2.
I always need to drag the item one below the one i want.

**Comment by jrief** [comment]
This probably is a configuration error.
Please checkout the example and retest with it.

**Comment by freskimo** [comment]
I followed the documentation...
Configuration is pretty straightforward so little chance of doing it wrong.

The order is descending in the admin view (not the model)

**Comment by jrief** [comment]
However, I can't reproduce it.

Since this is one of the most fundamental parts of adminsortable2, don't you think it would have been discovered by someone else already?

**Comment by freskimo** [comment]
You can reproduce this when doing the following:
```
#admin.py
class PortfolioAdmin(SortableAdminMixin, admin.ModelAdmin):
    ordering = ('-order',)
````

**Comment by jrief** [comment]
1. what sense does it make to add reverse ordering to the admin, if you want to order stuff.
2. why didn't you mention this in your first post? Do you really believe that it makes the life of us developers easier, if you hide such fundamental things.
I really want to close this now and won't answer anymore.

**Comment by freskimo** [comment]
1. You don't want new items being added to the bottom of the page. This means the admin has to scroll down the page the whole time. Or how do you solve this problem?

2. I noticed the ordering effected only after looking for making it reproducible.

**Comment by jrief** [comment]
OK, I got your point!
Please retry, using the latest version from GitHub. If that works for you, I'll release a new version on PyPI.
Thanks for your patience.

**Comment by freskimo** [comment]
@jrief I tested your commit and can confirm this fixes the issue.

Thank you for the quick reply and action!

**Comment by jrief** [comment]
Version 0.6.10 which fixes this issue is available from PyPI.

@freskimo  Thanks for you patience. The next time you report a bug, please write it in a way so that the author can reproduce it easily in his environment. Otherwise you risk to run into the same misunderstandings as we did before.

**Comment by kayadata** [comment]
hi jacob. The problem is not resolved i think.

Tested with Django==1.11.1 and django-admin-sortable2==0.6.11
