### ISSUE TITLE
JavaScript code doesn’t work on Firefox

### ISSUE THREAD

**Issue by merwok** [jrief/django-admin-sortable2#146]
Hello!  I have admin classes that work with Chromium but not Firefox.

Versions: Python 3.5.3, Django 1.10.6, django-admin-sortable2 0.6.10, jQuery (from django admin) v2.2.3, Firefox ESR 45.8.0.

Steps: follow docs, go to the admin page, create objects, reorder them.

Expected: POST requests to the update URL, order is preserved after page refresh.

Observed: no request, console logs: «The server responded: undefined» (from list-sortable.js:76, which is inside the error callback for the ``$.ajax`` call).

Stack trace:
 ![tmp](https://cloud.githubusercontent.com/assets/635179/24572800/18378b68-164a-11e7-9665-7bee147ace28.png)

**Comment by jrief** [comment]
Just retested with FF version 43 and 52, but they both work properly.
Please retest with an actual version.

**Comment by jrief** [comment]
Can I close this?

**Comment by merwok** [comment]
I don’t know what you meant with «retest with an actual version».  Firefox ESR 45 is the version from Debian testing.

**Comment by jrief** [comment]
I don't develop on Linux, so it's difficult to reproduce your environment. However I can confirm that with FF 43 everything works on MacOS 10.11.6.
Could you please send me the raw HTTP response causing this.
