### ISSUE TITLE
Sortable inline not appearing when DEBUG=False

### ISSUE THREAD

**Issue by mailbackwards** [jrief/django-admin-sortable2#151]
I have one `Content` model, and two different sortable inlines that link them: `RelatedContent`, and `ReadMoreRelatedContent`. They are very similar models/inlines, but when `settings.DEBUG` is set to `False`, only `RelatedContent` shows up; the `ReadMoreInline` does not appear. If I remove the sortable mixin or set `DEBUG` to `True`, both inlines appear as expected. Has anyone seen something like this before-- what could be the difference between these two models, and what would make `DEBUG=False` miss one of them? Any help appreciated-- thanks!

Python 2.7, Django 1.8

```python
### models.py

class RelatedContent(models.Model):
    content_item = models.ForeignKey(Content, related_name="reverse_related_content")
    content_relation = models.ForeignKey(Content, related_name="related_content")
    order = models.IntegerField(blank=False, null=False, default=0)

    class Meta:
        verbose_name_plural = 'Related content'
        ordering = ['order']

class ReadMoreRelatedContent(models.Model):
    source = models.ForeignKey(Content, related_name="read_more_targets")
    target = models.ForeignKey(Content, related_name="read_more_sources")
    order = models.IntegerField(blank=False, null=False, default=0)
    summary_text = models.TextField(blank=True, null=True,
        help_text=u'The text to use to populate the read-more link.')

    def __unicode__(self):
        return u'Read-more link: %s --> %s' % (
            self.source.headline, self.target.headline)

    class Meta:
        ordering = ['order']

class Content(models.Model):
    headline = models.CharField('Default headline', max_length=255,
        help_text=u'The default display headline')
    # more fields here... no M2M defined...


### admin.py

class RelatedContentInline(SortableInlineAdminMixin, admin.TabularInline):
    model = RelatedContent
    ordering = ['order']
    extra = 0
    fk_name = 'content_relation'
    raw_id_fields = ['content_item']
    verbose_name = 'Related content'
    verbose_name_plural = 'Related content'

class ReadMoreInline(SortableInlineAdminMixin, admin.TabularInline):
    model = ReadMoreRelatedContent
    extra = 3
    fk_name = 'source'
    raw_id_fields = ['target']
    verbose_name = 'Read more'
    verbose_name_plural = 'Read mores'

class ContentAdmin(admin.ModelAdmin):
    # some other attributes
    model = Content
    inlines = [RelatedContentInline, ReadMoreInline]

admin.site.register(Content, ContentAdmin)
```

**Comment by mailbackwards** [comment]
I've discovered that this is happening because of the help text on the `summary_text` field in Django 1.8. The help text triggers [this template line](https://github.com/jrief/django-admin-sortable2/blob/master/adminsortable2/templates/adminsortable2/tabular.html#L13), which fails because it's a gif rather than svg in Django<1.9. For now I can manually patch it (either by patching the template or adding the svg myself) but seems worth mentioning or fixing somewhere.

**Comment by jrief** [comment]
I looked at it myself two days ago, but was unable to understand its cause.
Please create a pull request on the documentation, in order to prevent others from having the same problem.
