### ISSUE TITLE
Sortable column not the first field

### ISSUE THREAD

**Issue by mtribaldos** [jrief/django-admin-sortable2#155]
Hi Jacob,

it seems there exists the limitation that the sortable column always is the first column in the result list. As normally it's supposed one orders the fields left to right according to their relevance, in many cases I find it would be more suitable that the sortable column were the last field (or maybe in any other position). Is there any way to accomplish this?

Regards.

**Comment by jrief** [comment]
Hmmm, seems to be a lot of work for little benefit.

Do you want to create a pull request?

We then would need an additional attribute in the ``ModelAdmin`` class, specifying which column this should be. This attribute could be named ``column_order_index`` (or any other self explaining name).

**Comment by mtribaldos** [comment]
In this PR, instead of adding any extra attribute, the position is inferred from the position of the order field in   `list_display` (first position, default behaviour, if it's not specified).
