### ISSUE TITLE
Feature request: Support Many-to-One relationships

### ISSUE THREAD

**Issue by mkoistinen** [jrief/django-admin-sortable2#178]
I would like to request support for Many-to-One relationships. In the normal Django way, a la:

````
# models.py

class ModelA(models.Model):
    ...

class ModelB(models.Model):
    model_a = models.ForeignKey('ModelA', ..., related_name='model_bs')


# admin.py

class ModelBInlineAdmin(SortableInlineMixin, admin.TabularInline):
    model = ModelA.model_bs.through
    ....

class ModelAAdmin(admin.ModelAdmin):
    inlines = ('ModelBInlineAdmin', ...)
    ....
````

I just tried it and it sadly fails. I had a look at the `django-admin-sortable2` code, looks like we just need a bit more introspection, but I didn't look _that_ deeply into it.

**Comment by jrief** [comment]
Hi Martin,
could you please line out in the example above where the ordering field shall be placed.
Unfortunately I don't understand what you intend to do.

**Comment by mkoistinen** [comment]
You know, I'm looking at that, and even I don't have a clue what I was attempting to convey. Please ignore it until I come across that situation again, then I promise I'll make a better ticket =). Sorry for the confusion (for both of us).
