### ISSUE TITLE
CKEditor support

### ISSUE THREAD

**Issue by dg1980** [jrief/django-admin-sortable2#184]
Hi,

sorting breaks CKEditor fields (official Django CKEditor package). Have you any ideas for integrate it in proper way?

I will be grateful for support.

Regards
Daniel

**Comment by matthiask** [comment]
You have to destroy the CKEditor instance before dragging begins and create the editor instance again after dropping.

Various Django-based CMS systems already solve this problem. You can probably build your own solution by listening to jQuery sortable's events (http://api.jqueryui.com/sortable/) and reusing the replace/destroy snippet from here: https://github.com/matthiask/feincms3/blob/master/feincms3/static/feincms3/plugin_ckeditor.js or somewhere else.

**Comment by dg1980** [comment]
Thank you very much.
