### ISSUE TITLE
use django.jQuery instead of global window.jQuery

### ISSUE THREAD

**Issue by Flui** [jrief/django-admin-sortable2#185]
`jQuery(function($) { ... });` seems a bit of inconvenient, as it uses the global jQuery instead of the one exported from django and it will cause an error if jQuery is not present yet.

So i would think of somethink like

```javascript
window.onload = function() {
    if (django.jQuery === undefined) {
        throw Error('jQuery is not present yet');
    } else {
       (function($) { ... })(django.jQuery);

    }
}
```

**Comment by jrief** [comment]
Django-Admin uses jQuery itself anyway, so I don't get your problem.

**Comment by gagnesteph** [comment]
If you use multiple librairies like for exemple django-modeltranslation and django-admin-sortable2

With a admin using: TranslationAdmin, SortableAdminMixin, admin.ModelAdmin

You have Jquery conflict and admin do not work properly.

Flui had it right suggesting the change!

**Comment by jrief** [comment]
Next version will run without jQuery. I'll switch to [SortableJS](https://sortablejs.github.io/Sortable/).
