### ISSUE TITLE
Ordering is not updated in the database

### ISSUE THREAD

**Issue by sachitad** [jrief/django-admin-sortable2#19]
Hi,

When I drag and drop the model datas from one row to another, they are not updated in the db. Thus when I refresh the page it's the same. What am I missing?

**Comment by leotsem** [comment]
Agree with @Hexcles, running the management command fixes the problem but it's not optimal.

@jrief would you consider a PR that runs this https://github.com/jrief/django-admin-sortable2/blob/master/adminsortable2/management/commands/reorder.py#L21 when all your records are equal to the field default value?
