### ISSUE TITLE
Jquery issue

### ISSUE THREAD

**Issue by Aupourbau** [jrief/django-admin-sortable2#202]
Hello,

I m getting this error in the console for Inline set up (SortableInlineAdminMixin, admin.TabularInline):
"Configuration for a django-adminsortable2 inline-tabular form is invalid."

It might be because of Django 2.1  moving to Jquery 3.3.1.

**Comment by Pinaz9** [comment]
After doing some research, I've come up with what I think might be the cause. In `inline-tabular.js`, we have this line:
https://github.com/jrief/django-admin-sortable2/blob/00a0c119d02b8df087e5cc2e9ff5ed8d083d35c1/adminsortable2/static/adminsortable2/js/inline-tabular.js#L5

It calls a method with one parameter.

Looking at that method in Django's source:

https://github.com/django/django/blob/9ec1a85c777a66e74cf3d8e10ecab113c411be1d/django/contrib/admin/static/admin/js/inlines.js#L148

we can see that it is expecting two parameters. Looking at the git blame for that line shows that this was not always the case.

**Comment by Aupourbau** [comment]
Thanks, I applied your fixes and it s perfect now.

**Comment by jrief** [comment]
@Aupourbau @Pinaz9 does this patch also work for older versions of Django, ie. those which use older versions of jQuery?

**Comment by Pinaz9** [comment]
I'm pretty sure it does not, as the old method simply did what I did in the params to get the selector. It only took one parameter, and that was the second one we're passing now, so if it simply drops the second parameter, it'll still error out.
