### ISSUE TITLE
feature request - specify JSON encoder (or support Hashid field)

### ISSUE THREAD

**Issue by eyesee1** [jrief/django-admin-sortable2#214]
Hi, 

Fairly easy feature request.

Allow override of the JSON encoder used in update_order (or make one that handles HashID fields) without throwing an exception. 

I ran into some trouble so I had to override the update_order method to stick an encoder in there
that calls str() on Hashids. https://github.com/nshafer/django-hashid-field

Thanks!

**Comment by jrief** [comment]
How would you like to make this overridable? Would you suggest doing this through a settings variable? Hmm, yes, this could make sense. Any name proposals?

**Comment by eyesee1** [comment]
On thinking about it further, casting the pk to a string should do the trick without breaking other things since Django already handles that. The problem is assuming the pk will always be an integer.
