### ISSUE TITLE
Ordering inlines with unique constraint don't work

### ISSUE THREAD

**Issue by markosep** [jrief/django-admin-sortable2#215]
Reordering with a unique constraint works in list view, but for some reason it won't work with inline items. Is this a bug or a feature?

This is the starting position:
<img width="528" alt="screen shot 2018-11-27 at 10 48 14" src="https://user-images.githubusercontent.com/26898255/49069818-e0e21680-f232-11e8-9961-cafd96733f70.png">

After I try to reorder and save, I get following:
<img width="528" alt="screen shot 2018-11-27 at 10 51 46" src="https://user-images.githubusercontent.com/26898255/49069849-f3f4e680-f232-11e8-8a41-cb6b48577912.png">

I have a constraint:
unique_together = ('cycle', 'ordinal')

Based on documentation, I assume adding a unique constraint works only on PostqreSQL. I'm fine with that limitation, if it allows me to add the unique constraint and to make sure that there can't be two objects with the same ordinal.

**Comment by jrief** [comment]
As the docs state, don't use unique constraints on the ordering field. In case you really have to, add a validator to the model and do it in the application instead of the database.

Always remember, that you can resort them using the management command.
