### ISSUE TITLE
Optional ordering starting from 1

### ISSUE THREAD

**Issue by ppeczek** [jrief/django-admin-sortable2#219]
I would like to treat ordering as pages for my urls. Unfortunately it starts from 0, which is very typical for developing, but for that certain use case it's a flow. I imagine that it could be developed by setting variable in my django settings like:

`ADMINSORTABLE_STARTS_WITH = 1`

That would change first value in ordering for 1.

What is your opinion on that feature?

**Comment by jrief** [comment]
By default, the `ordering` field is one-indexed, see https://github.com/jrief/django-admin-sortable2/blob/master/adminsortable2/management/commands/reorder.py#L27

If it's 0 in your configuration, there must be something wrong.
