### ISSUE TITLE
Django 2.1 gives error due to prefilling list_display_links

### ISSUE THREAD

**Issue by BrendaH** [jrief/django-admin-sortable2#220]
Django: 2.1.7
Admin sortable2: 0.7

I have a special admin page where I do not want anything to be a link to the item because users sorting the content are not necessarily allowed to edit the items that can be sorted.
So, as per the Django docs, I set my settings like this:

```
    model = WhoIsWhoFunction
    list_display = ['on_whoiswho', 'functionname', ]
    list_display_links = None
    list_editable = ['on_whoiswho']
    sortable_by = []  # Disable sorting on all columns since adminsortable2 will take care of that
```

And then, to my surprise I get the following error:

`<class 'pe.admin.WhoIsWhoFunctionAdmin'>: (admin.E123) The value of 'on_whoiswho' cannot be in both 'list_editable' and 'list_display_links'.`

This is caused by [the code here](https://github.com/jrief/django-admin-sortable2/blob/master/adminsortable2/admin.py#L101):
```
        if not self.list_display_links:
            self.list_display_links = (self.list_display[0],)
```
This code was there from the beginning, but why? If a developer thinks list_display_links should be empty, why do you fill it? Except for removing the default order field from that list, it does not seem to be used for anything, so why is it set?

Commenting these lines out solves my problem and does not seem to have a negative effect.
(Changing the order of my list_display fields so a different field than 'on_whoiswho' gets added to list_display_links also removes the error, but that gives me an unwanted link.)

**Comment by BrendaH** [comment]
It was fixed on April 24, but then the removed code was re-added again on[ June 19th](https://github.com/jrief/django-admin-sortable2/commit/d45ce2c56c9ba7c0057769cbeabcea4b142a851e#diff-c008b91f4b66a2801042a09032bc38ed). Reintroducing the behaviour. Why is that?

Is there a non-hacky way to circumvent this if someone does not want the items to be links?

**Comment by jrief** [comment]
Because it broke the behaviour of other apps using it.
If you are using something like `list_display_links = None`, then  please provide a pull request which behaves properly for that use-case, rather than just removed two lines of required code.

How about adding a method `has_change_permissions()` which always returns `False`?

**Comment by BrendaH** [comment]
I'm not sure I follow. Can you give me an example of which apps use it for what exactly and how they break? Is the problem that these apps set the `self.list_display_links` to None and expect it to be changed to an actual list instead of None? In this case, they would depend on sortable to change the default Django API, which does not seem right. Or do they not define a list_display_links which is by default set to an empty tuple by Django, which then leads to problems further along the line? For this case, I could not figure out how the two lines under discussion would make a difference.

It looks like these two lines are intended to mimic Django's default value for `list_display_links`? The Django code itself does a check on list_display_links which would perhaps be a better way to handle a falsy (i.e. empty list or None) value of list_display_links in the admin sortable code.
Django does the following

https://github.com/django/django/blob/8687fbe034ac5eec20e0948b98eb8a2f0b1431a1/django/contrib/admin/options.py#L947-L957


In my usecase, the first value from `list_display` is also in `list_editable`, which triggers the error I showed.  However even without `list_editable`, the error goes away but the current sortable code basically ignores the `list_display_links` value of None and causes Django to render the first field as a link which I need to not happen.

For my use case, it would probably be sufficient for sortable to leave `list_display_links` untouched when it is `None` (and keep the existing code for other falsey values, such as the default empty tuple). However I can not think of a use case where this existing code is needed, so I want to rather understand that use case and maybe find a better solution for both cases.

Regarding you suggestion about `get_change_permission()`, I think you mean to use that method to remove change permissions for this view? I can not set the change permission to False because I need it for my interface. I have a column of checkboxes that must be editable on the changelist page directly, without having a link to the underlying change page (which will only confuse users of this particular changelist). If I remove the change_permission these checkboxes transform into displayed boolean values, making it impossible to change them.

If you can give me an example of the breaking use cases I can try to look into it and come up with a solution that works for everybody.

**Comment by jrief** [comment]
@BrendaH I believe, I found a solution which handles all use-cases. Please try out the latest master branch and share your experience. If that solution works well for you, I will release version 0.7.3.

**Comment by BrendaH** [comment]
This works for me. :-)
I can now set list_display_links to None and have the required order of fields in list_display and the required field in list_editable without any errors.
I'm looking forward to the new release. Thanks!

**Comment by jrief** [comment]
Thanks for reporting this bug.
Version 0.7.3 has been released:
https://pypi.org/project/django-admin-sortable2/
