### ISSUE TITLE
Visibly updating order numbers in real time - right after moving an item

### ISSUE THREAD

**Issue by vangravs** [jrief/django-admin-sortable2#224]
Hello
Great plugin, works wondrously, many thanks for creating this!!!

I wish to have the ordering with DAS2, display that value and have it updated after each move. Therefore I made a simple function in my models:

`    def current_order(self):
        item_order = self.order + 1
        return item_order`

but the "problem" is that the values update only after a page refresh and I cant figure out how to change these order values in real time, after each drag. It kinda gets confusing when sorting many list items.

**Comment by jrief** [comment]
In the list view, the number used to keep track of the sorting, is updated in realtime, ie. every time you drag the item and drop it somewhere else.
Therefore I don't understand what you want to change.

**Comment by vangravs** [comment]
The thing is - the numbers are indeed updated in real time, but I wish to make them visible. Currently, at least in my case, these numbers are not visible, only the are to drag them by, just like in the exaple. I made them visible in a very simple way due to lack of skill on my part. but these numbers refresh only after a page refresh.
![Screenshot from 2019-07-15 12-06-08](https://user-images.githubusercontent.com/37309220/61205536-f7bd7680-a6f8-11e9-8ee9-f89604dc62f9.png)

**Comment by jrief** [comment]
OK, got it!
What about integrating the column **SAVE ORDER** into the first column **ORDER**?
With some CSS, that should be doable. Do you want to create a pull request for it?

**Comment by jrief** [comment]
This can be implemented easily using a method on the model admin class. Since it is a very rare use-case, I see no reason to implement something.
