### ISSUE TITLE
Release history not updated since 0.6.17

### ISSUE THREAD

**Issue by adamchainz** [jrief/django-admin-sortable2#225]
Hi,

Thank you for this project.

The [release history](https://django-admin-sortable2.readthedocs.io/en/latest/changelog.html) doesn't seem to have been updated since version 0.6.17, which came out Dec 4, 2017, so upgrading is a bit hard as I don't know if I need to change anything about my project. Or am I missing something?

Thanks,

Adam

**Comment by adamchainz** [comment]
Ah no, I see it is updated at https://github.com/jrief/django-admin-sortable2/blob/master/docs/source/changelog.rst , but Read The Docs doesn't seem to have been updated with all those changes!

**Comment by jrief** [comment]
I've just rebuilded the docs manually. Thanks for reporting!

**Comment by adamchainz** [comment]
👌
