### ISSUE TITLE
<input> and <select> are not selectable with mouse click in Firefox

### ISSUE THREAD

**Issue by erhan-** [jrief/django-admin-sortable2#23]
Hey, 

thanks for your nifty tool first.

So I'm using this application with django cms 3 and I have following problem with inline sortables:

When I try to click on a <input> or <select> tag, I automatically start dragging that object. As a workaround I can click with right click on that input field first and then it is selected and I can write in it or I can tab till to the input field.

Strangely this problem is only in firefox. On a webkit based browser there is no problem.

**Comment by nicholasserra** [comment]
Also see it on FF 35 Mac.
