### ISSUE TITLE
Conflict with django-tagulous

### ISSUE THREAD

**Issue by alex-msk** [jrief/django-admin-sortable2#239]
Try to use django-admin-sortable2 with django-tagulous (https://github.com/radiac/django-tagulous). 

As a result, neither "django-tagulous" nor "django-admin-sortable2" work.

I get an error in the console

`TypeError: $el.select2 is not a function. (In '$el.select2(args)', '$el.select2' is undefined)`

**Comment by GHPS** [comment]
> I get an error in the console 
> `TypeError: $el.select2 is not a function. (In '$el.select2(args)', '$el.select2' is undefined)`

"django-tagulous" comes with the select2 js library included. This could be the cause
of the problem - which can be verified by loading only sortable2 and select2

`<script src="/js/select2.min.js"></script>`

Does this raise an error as well?
