### ISSUE TITLE
Original values word-wrap out of view in TabularInlines

### ISSUE THREAD

**Issue by alanwj** [jrief/django-admin-sortable2#24]
Any time the original value of a model instance (as determined by its __str__ method) contains a character upon which word wrap could occur, such as space or dash, the rest of the value is word wrapped out of visibility.

As an example, create a TabularInline for the following model:

```
from localflavor.us.models import PhoneNumberField

@python_2_unicode_compatible
class PhoneNumber(models.Model):
    other_model = models.ForeignKey('OtherModel')
    number = PhoneNumberField('phone number')

    order = models.PositiveSmallIntegerField(default=0)

    class Meta(object):
        ordering = ('order',)

    def __str__(self):
        return self.number
```

After saving the phone number '123-456-7890', the original value will be subsequently displayed as '123-'.

**Comment by jrief** [comment]
Please retry with django-1.9. CSS styling change to the better. Otherwise reopen this issue.
