### ISSUE TITLE
Could it work just off ModelAdmin.ordering

### ISSUE THREAD

**Issue by tolomea** [jrief/django-admin-sortable2#248]
It seems to respect ModelAdmin.ordering but still complains at startup if that is set but Model.Meta.ordering is not.

We have a standing policy of not using Model.Meta.ordering as it it adds ordering to all queries even if they don't need it (unless you remember to override) and that increases database overhead.

We also have ordering on all ModelAdmins and Inlines, which is how I noticed that it does seem to respect ModelAdmin.ordering.

**Comment by adamrt** [comment]
I was looking at this to see if its possible to override this myself, but the code looks like it actually does what you are requesting. Are you putting it in `ModelAdmin.Meta.ordering` or `ModelAdmin.ordering`?

https://github.com/jrief/django-admin-sortable2/blob/86a44c759fc85f1a1ea87aaf78bd32b6daf7692b/adminsortable2/admin.py#L33

**Comment by jrief** [comment]
I will use this [ordering field](https://docs.djangoproject.com/en/4.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.ordering)
and only fallback to the model's Meta ordering field.

Is that OK for you?

**Comment by codingjoe** [comment]
@jrief there appears to be a problem, though. Since the admin must define ordering explicitly. I believe it would be better to call `ModelAdmin.get_ordering`. Yet, this cannot be done during admin initialization, since this method requires a request.

**Comment by jrief** [comment]
In version 2 you can set the ordering field in the sortable ModelAdmin and you do not require to set it in the model's Meta class.

Please check the new testapp for a demo on how this is handled.
