### ISSUE TITLE
Question: how to use drag-drop and list_editable together?

### ISSUE THREAD

**Issue by IRemsha** [jrief/django-admin-sortable2#262]
I can show 2 column order (drag-drop) and _order (just number) together, but maybe you have some idea how do field _order editable from list. I want set value in two ways.

```
class ToolAdmin(admin.ModelAdmin):
   list_editable = ('order',)
   list_display = ('title_en', '_order', 'order')
    
    def _oreder(self, obj):
        return obj.order
```

**Comment by jrief** [comment]
Setting the `order` manually is a very bad idea, because inevitably you will create entities with the same order value.
