### ISSUE TITLE
SortableInlineAdminMixin not firing order request to backend

### ISSUE THREAD

**Issue by behconsci** [jrief/django-admin-sortable2#264]
I have set up exactly like this: 

```
from django.contrib import admin
from adminsortable2.admin import SortableInlineAdminMixin
from models import MySubModel, MyModel

class MySubModelInline(SortableInlineAdminMixin, admin.TabularInline):  # or admin.StackedInline
    model = MySubModel

@admin.register(MyModel)
class MyModelAdmin(admin.ModelAdmin):
    inlines = (MySubModelInline,)

```

objects already existed. But I reordered and also changed the values in DB from 0 to 1, 2, 3, ... 

but still, if I order in admin inlines, I see no change request beint sent to backend: 

![image](https://user-images.githubusercontent.com/10358323/107106502-46c38300-682c-11eb-8a83-eb3e80d49e7a.png)

Thus, order is not persistent. 

What am I doing wrong?

**Comment by jrief** [comment]
sorting `InlineAdmin`s is send to the server when clicking the `Save` button.

**Comment by interfector18** [comment]
I'm having the same issue, it doesn't fire when clicking save. Any ideas?
