### ISSUE TITLE
Please add Django 3.2 support

### ISSUE THREAD

**Issue by leon-matthews** [jrief/django-admin-sortable2#270]
The only thing that could make this fabulous package even better would be Django 3.2 support.

**Comment by jrief** [comment]
Did you test to force an installation in Django-3.2 – and if, does it stell work?

**Comment by leon-matthews** [comment]
I just did so, and everything _seems_ to work just fine.

Because of the line `install_requires=[ 'Django>=1.8,<3.2',]` in the _setup.py_  file, I had to force the install:

```
$ pip install -r requirements.txt
$ pip install --ignore-installed django-admin-sortable2==0.7.8 
```

The only tiny issue was a deprecation warning printed when I ran my unit tests:
```
/lib/python3.8/site-packages/adminsortable2/admin.py:144: 
    RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
    url(r'^adminsortable2_update/$',
```

**Comment by jhernandez-at-wiris** [comment]
Aree there updates about this? Is there a plan to add Django 3.2?

**Comment by marksweb** [comment]
@jhernandez-at-wiris I've got a draft PR which tests against 3.2 and removes the restriction for django 3.2 on the package. #271 

This needs some actual testing I think to verify that things are ok. I've only got as far as updating my requirements so far. Feel free to install from my branch & give it a test;

`-e git://github.com/marksweb/django-admin-sortable2.git@master#egg=django-admin-sortable2`

**Comment by motu55** [comment]
I just installed your in my projekt with django 3.2 and it works like a charm.

**Comment by marksweb** [comment]
@motu55 Excellent, thank you for confirming.

**Comment by jhernandez-at-wiris** [comment]
@marksweb everything works fine! 😄

**Comment by marksweb** [comment]
Please upgrade to version `1.0`

**Comment by leon-matthews** [comment]
Thank you very much for this, much appreciated!
