### ISSUE TITLE
How can I make bigger grey area, checkbox's text and checkbox itself ? 

### ISSUE THREAD

**Issue by cprog** [jrief/django-admin-sortable2#278]
Hello everyone,
How I can easily and properly make bigger text("Delete"), , ui-handler (gray area) and checkbox ?
Is there any option ?
![django-admin-sortable](https://user-images.githubusercontent.com/8316463/122377270-9ac63d00-cf6d-11eb-8627-4dd9dd199595.png)

**Comment by jrief** [comment]
Play a little with with CSS.
