### ISSUE TITLE
Double new item row added by SortableInlineAdminMixin + TabularInline

### ISSUE THREAD

**Issue by m-melis** [jrief/django-admin-sortable2#284]
Just upgraded to django 3.2 and found the following. Using `TabularInline` with `SortableInlineAdminMixin` a double "new item" row is added. This does not happen in the case of the `StackedInline`.

django-admin-sortable2 version 1.0.1

SortableInlineAdminMixin, admin.TabularInline:
![image](https://user-images.githubusercontent.com/7879584/135446859-b615fe4c-ce95-4208-a2fb-aec25f664da9.png)

admin.TabularInline:
![image](https://user-images.githubusercontent.com/7879584/135446977-41198b24-7693-48ae-8816-c960bdcbab58.png)

SortableInlineAdminMixin, admin.StackedInline:
![image](https://user-images.githubusercontent.com/7879584/135447042-17e36a22-43fb-4321-aefb-80fc93b123b3.png)

Thanks for your work.

**Comment by jrief** [comment]
If you downgrade to version 1.0, does it still happen? I just changed one CSS class, 🤔

**Comment by m-melis** [comment]
Working fine with version 1.0 and Django 3.2, yes!

![image](https://user-images.githubusercontent.com/7879584/135470207-27a1eaf7-f470-4411-9c47-ed56ee2929bd.png)

**Comment by amureki** [comment]
Greetings fellows,

I can confirm that 1.0.1 (and #273 in particular) leads to the described issues (and broken inline behaviour in general).

![CleanShot 2021-09-30 at 17 16 29](https://user-images.githubusercontent.com/627183/135483368-c289d6c7-e692-4d84-b8cf-75d7ca5ebe3b.gif)


Our setup:

- Python 3.9
- Django 3.2
- default Django admin
- django-admin-sortable2 1.0.1

And when rolling back to django-admin-sortable2 1.0.0 all works as expected.
I wonder if we can fix custom admin interfaces and CSS frameworks in some other ways, however I don't see a good solution yet. :(

Best,
Rust

**Comment by jrief** [comment]
Without having a setup where I can test this, could you please do me a favor:
Use the latest version from GitHub and try again. If that helps, I'll release version 1.0.2

**Comment by m-melis** [comment]
Working fine again after installing the latest github version. 👍🏼

**Comment by jrief** [comment]
[Version 1.0.2](https://pypi.org/project/django-admin-sortable2/) is available.
