### ISSUE TITLE
1.0.1 - CSS error causing empty-rows to show

### ISSUE THREAD

**Issue by nc-Swift** [jrief/django-admin-sortable2#285]
This line in sortable.css:
```
div.inline-group table.ui-sortable tr.form-row {
    display: table-row;
}
```
Is overruling this line in forms.css from django admin:
```
.empty-form {
    display: none;
}
```
It is causing empty rows on inlines to show, heavily confusing users.

**Comment by marksweb** [comment]
@nc-Swift Did 1.0.2 fix this?

**Comment by nc-Swift** [comment]
It looks like it did, yes. I had overriden admin/css/form.css to have:

`.empty-form {
    display: none !important;
}`

I was able to remove that, and it seems like the rule isn't being overruled by sortable.css anymore.
