### ISSUE TITLE
Question: Is there a way to Hook into the saving endpoint?

### ISSUE THREAD

**Issue by selected-pixel-jameson** [jrief/django-admin-sortable2#297]
Is there a specified way of triggering an additional event to happen when the order is changed? 

For example lets say I want to update all of the models that are related to the item which I just changed the order on.

**Comment by jrief** [comment]
> Is there a specified way of triggering an additional event to happen when the order is changed?

You mean on the server, or on the client?

**Comment by selected-pixel-jameson** [comment]
I actually just realized it appropriately triggers the post_save signal, so I'm able to tie into the action this way. 

Thank you!
