### ISSUE TITLE
Bug: ValueError: The file 'adminsortable2/js/adminsortable2.js.map' could not be found

### ISSUE THREAD

**Issue by benedikt-bartscher** [jrief/django-admin-sortable2#302]
Hey there, with version 2.0.0 my collectstatic always complains about the missing map file adminsortable2/js/adminsortable2.js.map:

```ValueError: The file 'adminsortable2/js/adminsortable2.js.map' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7fd3ede8dba0>.```

**Comment by jrief** [comment]
Please check if you have a file named `staticfiles.json`. If so delete it and rerun `collectstatic`.

**Comment by benedikt-bartscher** [comment]
Thanks, I already did that. I will investigate this evening.

**Comment by benhowes** [comment]
I'm also seeing this with v2.0, downgrading to 1.x got my heroku build working again.

**Comment by jrief** [comment]
Have you ever used the pre-release, ie. django-admin-sortable2-2.0rc0 ? In that version I forgot to remove `adminsortable2/js/adminsortable2.js.map` after the build. In version 2.0 this has been done.

Anyway, `staticfiles.json` is generated by `ManifestStaticFilesStorage`, so please check docs on how to fix this.

**Comment by amureki** [comment]
Hey everyone!

@jrief I stumbled upon the same issue. I did download the package manually from PyPI here:
https://pypi.org/project/django-admin-sortable2/#files (SHA: c3c5629368d982a914c89c0017df62ec4d4319ac77c163d972a237a7229350c8)
And it contains JS file under `adminsortable2/js/adminsortable2.js` which has a reference to `adminsortable2.js.map` and it fails during fresh `collectstatic` (no `staticfiles.json` in my files).

So, it seems to be that uploaded to PyPI archive is different from 2.0 version of GitHub. Do you think it could be the case?

Best,
Rust

**Comment by jrief** [comment]
This should be fixed in version 2.0.1.
It seems as if ManifestStaticFilesStorage event reads the comments in files. Therefore the file `adminsortable2.js.map` was allegedly missing.

**Comment by amureki** [comment]
@jrief thanks for a quick fix, can confirm, the reference is gone in 2.0.1! 🚀
