### ISSUE TITLE
CSRF Errors since version 2

### ISSUE THREAD

**Issue by benedikt-bartscher** [jrief/django-admin-sortable2#303]
Since version 2 all /adminsortable2_update/ POST requests are failing with an CSRF error (Status Code 403) for me.
![image](https://user-images.githubusercontent.com/31854409/161546789-32512f47-3c7d-48dd-aa61-8af47736f22b.png)

**Comment by jrief** [comment]
Please check that the preceding GET-request sets the Cookie named `csrftoken`. That value is parsed and added to the POST header.

**Comment by benedikt-bartscher** [comment]
It does not, it only sets a session id. I am using: `CSRF_USE_SESSIONS = True`
Logs:
`Forbidden (CSRF token from the 'X-Csrftoken' HTTP header incorrect.): /admin/myapp/mymodel/adminsortable2_update/`

**Comment by jrief** [comment]
fixed in version 2.0.2

**Comment by benedikt-bartscher** [comment]
works fine, thanks!
