### ISSUE TITLE
Uncaught error when using SortableAdminBase in admin view

### ISSUE THREAD

**Issue by avelosa** [jrief/django-admin-sortable2#309]
Seeing the same error as described in [https://github.com/jazzband/django-admin-sortable/issues/256](https://github.com/jazzband/django-admin-sortable/issues/256)

python version == 3.9.11
Django version == 4.0.4
adminsortable2 version == 2.0.3

It's a little bit more of a pain for us because we have cypress ui automation tests that fail due to the console error.

FWIW I think there are a couple issues:

1.  the django admin change_list.html template is missing the element with `id="admin_sortable2_config"`. In the JavaScript class `SortableBase` the constructor  does:
`this.config=JSON.parse(document.getElementById("admin_sortable2_config")` 
and thus the error mentioned above. `SortableAdminBase` is missing the change_list template override.

2. In the JS the `ActionForm` class assumes an element with `id="changelist-form-step"` exists. The following error appears in the browser console:
```
Uncaught TypeError: this.stepInput is null
    be http://localhost:8000/static/adminsortable2/js/adminsortable2.min.js:1
    <anonymous> http://localhost:8000/static/adminsortable2/js/adminsortable2.min.js:1
    EventListener.handleEvent* http://localhost:8000/static/adminsortable2/js/adminsortable2.min.js:1
    <anonymous> http://localhost:8000/static/adminsortable2/js/adminsortable2.min.js:1
```
I think this is due to `SortableAdminBase` not having `action_form = MovePageActionForm` set.

3. Probably not an issue for most Django users: we have admin users who are not superusers and so we restrict access to the admin change list dropdown select element and do not render it. This element  matches the query selector `select[name="action"]` in `ActionForm`.  I think it would be helpful if the conditional for creating a `new ActionForm` in the `window.addEventListener` function would check for the `select[name="action"]` element in addition to the `#changelist-form` element.

... I'll probably open a pull request.

**Comment by jrief** [comment]
In order to reproduce this error, please follow the steps described in 
https://django-admin-sortable2.readthedocs.io/en/latest/contributing.html#run-the-demo-app

You may clone the repository, add your model changes to the `testapp`, and commit it. I then will try to run it in my environment.

**Comment by dpp-name** [comment]
The case of non-sortable model having sortable inlines is not supported in v2x, but was supported in v1x

Upgrading from v1.0.4 it tells you `{} must inherit from SortableAdminBase since {} inherits from SortableInlineAdminMixin` if you do so it gives an error `Model {model.__module__}.{model.__name__} requires a list or tuple 'ordering' in its Meta class`

**Comment by fidelitas** [comment]
Thank you for fixing this @jrief 🌞
