### ISSUE TITLE
Handle-bar to drag items is blocking access to the item's fields

### ISSUE THREAD

**Issue by mnieber** [jrief/django-admin-sortable2#310]
In version 1 the handle bar is to the very left, and in version 2 it stretches across the item. Unfortunately, in the latter case it can overlap a field. This is especially a problem in the case of a checkbox, which is completely covered and not clickable anymore. I'm happily using version 1 so this is not urgent for me, but still I wanted to report it.

**Comment by jrief** [comment]
could you please share a screenshot, and maybe the `list_display` variable.

**Comment by mnieber** [comment]
Okay, I see what's going on now. I changed the style of my admin page to vertically compress the inlined items (I forgot all about that), this is why it overlaps.
