### ISSUE TITLE
Custom Form breaks reordering due to JavaScript error

### ISSUE THREAD

**Issue by caramdache** [jrief/django-admin-sortable2#311]
I am trying to use a custom form. But drag-and-drop reordering works only once and produces a JavaScript error, after which drag-and-drop is no longer possible.

When I remove the `form =` statement, reordering works beautifully with no JavaScript error.

What am I missing? Could this be an inheritance issue? But I could not find a solution by looking at the code.

```python
class DynamicFilterTermInlineFormSet(CustomInlineFormSet):
    pass

class DynamicFilterTermInlineForm(forms.ModelForm):
    class Meta:
        model = DynamicFilterTerm
        fields = ('op', 'field', 'lookup', 'value')

class DynamicFilterTermInline(SortableInlineAdminMixin, DynamicFilterInline):
    model = DynamicFilterTerm
    # form = DynamicFilterTermInlineForm # Drag-and-drop sorting works properly
    form = DynamicFilterTermInlineForm   # Drag-and-drop fails the 2nd time
    formset = DynamicFilterTermInlineFormSet
```

**Comment by caramdache** [comment]
It turns out the `order` field was missing from the Form `fields`. This prevented drag-and-drop from working.

It might be word adding this to the documentation (as well, by the way, as telling people to run `collectstatic` after installation).

**Comment by jrief** [comment]
> It might be word adding this to the documentation

Here: https://django-admin-sortable2.readthedocs.io/en/latest/usage.html#prepare-the-model-classes

> telling people to run `collectstatic` after installation

Here: https://docs.djangoproject.com/en/4.0/ref/contrib/staticfiles/#collectstatic
But presumably you meant `reorder`, which is documented here:
https://django-admin-sortable2.readthedocs.io/en/latest/usage.html#initial-data

in short: RTFD

**Comment by caramdache** [comment]
> Here: https://django-admin-sortable2.readthedocs.io/en/latest/usage.html#prepare-the-model-classes

Does this talk about django Forms? I don’t think so. 

> Here: https://docs.djangoproject.com/en/4.0/ref/contrib/staticfiles/#collectstatic But presumably you meant `reorder`, which is documented here: https://django-admin-sortable2.readthedocs.io/en/latest/usage.html#initial-data

Does django-admin-sortable2 installation manual ask users to runcollectstatic? I don’t think so. Not all third party apps require collectstatic to be run. Yours does. It’s not described. 

Please RTFQ.
