### ISSUE TITLE
Storing new Inlines not working in version 2

### ISSUE THREAD

**Issue by 21adrian1996** [jrief/django-admin-sortable2#312]
I am trying to store a new object in an SortableInlineAdminMixin:

```
from django.contrib import admin

@admin.register(MyOtherModel)
class MyOtherModelAdmin(admin.ModelAdmin, SortableAdminBase):
    inlines = [MyInline]


class MyInline(SortableInlineAdminMixin, admin.TabularInline):
    model = MyModel
    extra = 3
    ordering = ('order',)
```

Throws the error `getattr(): attribute name must be string` in `adminsortable2/admin.py, line 461, in save_new` on line `order_field_value = getattr(obj, self.default_order_field, None)`

The configuration works with 1.0.4 but not with 2.0.4.

Is there a new configuration or what am I missing?

**Comment by jrief** [comment]
Could you please fork the `testapp` and configure it in a way, so that I can reproduce that error.
Please read section on [how to report bugs](https://django-admin-sortable2.readthedocs.io/en/latest/contributing.html#reporting-bugs).

**Comment by ahmedsafadii** [comment]
same issue

**Comment by ahmedsafadii** [comment]
there is no request even goes in the network when finish the draging

**Comment by jrief** [comment]
Inlines have to be saved explicitly. This was already the case for version 1.

**Comment by ahmedsafadii** [comment]
@jrief any fix?

**Comment by jrief** [comment]
@ahmedsafadii I have no intentions to change this, so it probably will remain forever.

**Comment by im-n1** [comment]
Just ran into this issue and I can confirm there is a real bug. 

In `__init__()` method [here](https://github.com/jrief/django-admin-sortable2/blob/master/adminsortable2/admin.py#L432) you allow `default_order_field` to be `None`. But later in `save_new()` method [here](https://github.com/jrief/django-admin-sortable2/blob/master/adminsortable2/admin.py#L467) you call this `getattr(obj, self.default_order_field, None)` which in case of `default_order_field` is `None` raises an exception since `getattr()` requires to be a `string`:

```
In [2]: getattr(object(), "")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 getattr(object(), "")

AttributeError: 'object' object has no attribute ''

In [3]: getattr(object(), None)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 getattr(object(), None)

TypeError: getattr(): attribute name must be string
```

**Comment by jrief** [comment]
@im-n1 could you please give me full instructions on how to reproduce this bug.

**Comment by im-n1** [comment]
Sadly I can't because it happens on a project I'm just a small part and I don't have a full understanding of the whole party. However just looking into your code the issue is obvious. I guess it can be fixed right away.

**Comment by jrief** [comment]
@im-n1 then fork this repository, adopt one of the examples so that you can reproduce it there, and tell me where I can find it on GitHub. 

If you want me to fix rarely occurring bugs on OSS, then you have to invest some time as well.

**Comment by alchemistOfWeb** [comment]
I had the simular problem. I solved it by putting SortableAdminBase as first in inheritance.
incorrect: `class MyOtherModelAdmin(admin.ModelAdmin, SortableAdminBase):`
correct `class MyOtherModelAdmin(SortableAdminBase, admin.ModelAdmin):`

**Comment by im-n1** [comment]
Thats what I already have. But it doesn't fix the obvious bug in code.

**Comment by jrief** [comment]
@im-n1 how about my [proposal from December](https://github.com/jrief/django-admin-sortable2/issues/312#issuecomment-1340060176)?

**Comment by im-n1** [comment]
@jrief sadly I have no time to do that.

**Comment by topiaruss** [comment]
Surely ordering = ('order',) should be under class Meta?

```
class Meta:
    ordering = ("order")
```

**Comment by jrief** [comment]
@BigglesZX would you like to create a page in the docs section with recipes, when combining django-admin-sortable2 with other libraries?

**Comment by BigglesZX** [comment]
@jrief Sure, I'll try and look at that later today.
