### ISSUE TITLE
UX suggestions for sortable inlines

### ISSUE THREAD

**Issue by flbraun** [jrief/django-admin-sortable2#319]
Hi @jrief!

we at @boxine are now using your new sortable inlines, and it's working great! However, we made a few visual adjustments that we think the core project would benefit from:

1. The dotted 'drag anchor' should have a drag pointer, not a resize pointer.
2. We slightly enlarged the send to top/bottom buttons. We found them too hard to click accurately in their initial size for users with bad mouse skills and especially touchpad users.
3. We added a title to the top/bottom buttons, so users have a chance to find out what effect they'll trigger when clicked.

Here's how it looks:
![Peek 2022-06-29 11-47](https://user-images.githubusercontent.com/15526835/176409856-4a5cbd73-e490-432d-be11-584f7901bd8b.gif)

The changes should be easy to implement. I'd supply a PR if you agree with them.

**Comment by flbraun** [comment]
The changes to the drag area and the tooltip are looking great! However, regarding the button size:
Are you sure space in `TabularInline` is an issue? We set the border width to exactly `7px`, which yields the result displayed in the animation in my original post. That looks like the sweet spot between usability and visuals to us. Would you reconsider?

**Comment by flbraun** [comment]
@jrief Any update on this?

**Comment by jrief** [comment]
@flbraun please go ahead.

btw. In 99% of my use cases, I always use `StackedInlineAdmin`-s.

**Comment by flbraun** [comment]
>btw. In 99% of my use cases, I always use StackedInlineAdmin-s.

That's funny, for us it's 99% `TabularInline`.

>please go ahead.

Sorry, I don't understand. What do you want me to go head with? I asked you if you'd reconsider your decision regarding the button size, and increase it to `7px` for `TabularInline`.

**Comment by jrief** [comment]
I wanted to say to please go ahead with a pull request, and fit the button to your needs.
