### ISSUE TITLE
Add to the documentation that you cannot leave the default=0 model if there are records in the database.

### ISSUE THREAD

**Issue by smurfikk** [jrief/django-admin-sortable2#334]
Add to the documentation that you cannot leave the default=0 model if there are records in the database. We need unique values for the "order" field. I spent about 30 minutes looking for the problem!!!

**Comment by jrief** [comment]
It's documented here: https://django-admin-sortable2.readthedocs.io/en/latest/usage.html#initial-data
and I also wrote that you shall not use `unique` on the "order" field.
