### ISSUE TITLE
Installation issues.

### ISSUE THREAD

**Issue by c0d33py** [jrief/django-admin-sortable2#335]
when i try to install this package i get this error message because this package is not compatible with `Django==3.2.16`.

`django-admin-sortable2` requires Django 4.0 or higher but i have `Django==3.2.16` installed in my project so i can't install this package 
if i install Django 4.0 or higher my project will not work because the other packages are not compatible with `Django 4.0` or higher 

i need to install this package to make my project work so please help me to solve this problem 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. 
This behaviour is the source of the following dependency conflicts.
django-tenants 3.4.2 requires Django<=4.1,>=2.1, but you have django 4.1.2 which is incompatible.
django-celery-beat 2.2.1 requires Django<4.0,>=2.2, but you have django 4.1.2 which is incompatible.
```

**Comment by jrief** [comment]
If you want to stick with Django<4 you have to use version 1.0.4.
