### ISSUE TITLE
Exception Value: Expression contains mixed types: TextField, IntegerField. You must set output_field.

### ISSUE THREAD

**Issue by jedie** [jrief/django-admin-sortable2#341]
I get this error here:
![grafik](https://user-images.githubusercontent.com/71315/209081859-7f18c916-b53d-46ab-b052-427f93c5c33a.png)

It's here:
https://github.com/jrief/django-admin-sortable2/blob/7bb2640fb35939d52248756b089ae27241d313f4/adminsortable2/admin.py#L339-L342

I just add a poor work-a-round:
```
    def get_max_order(self, request, obj=None):
        return 0
```

**Comment by jrief** [comment]
Does this mean that method `get_max_order` returns a string rather than a number?

What's the field type of the field you're using for ordering? Please show me your model.

**Comment by jedie** [comment]
Model is here: https://github.com/jedie/PyInventory/blob/140edd20b024af2db974cd3a5cecc6e7285bf765/src/inventory/models/item.py#L25

Work-a-round added here: https://github.com/jedie/PyInventory/commit/4f16e6de3410d0de9b0e9c665a180c1bf5c1bfc6#diff-06e796a58db7d52539c1cf5d11602d4bfbd0f96072b0de6a4c54ab55b0795285R88-R90

**Comment by jrief** [comment]
well, you're [using a TextField](https://github.com/jedie/PyInventory/blob/140edd20b024af2db974cd3a5cecc6e7285bf765/src/inventory/models/base.py#L132) as ordering variable. For obvious reasons this can't work and should have been discovered by yourself in the first place.
