### ISSUE TITLE
DAS2 v2.x appears to assume fields are in Mutable Containers

### ISSUE THREAD

**Issue by mkoistinen** [jrief/django-admin-sortable2#346]
https://github.com/jrief/django-admin-sortable2/blob/7bb2640fb35939d52248756b089ae27241d313f4/adminsortable2/admin.py#L496-L500

This code here makes the assumption that the provided Iterable of `fields` is mutable. Tuples are not and Tuples have been the traditional container for declaring fields in Django models for a long time.

Ideally, this would do something more like: 

    def get_fields(self, *args, **kwargs):
        **fields = list(super().get_fields(*args, **kwargs))**
        if self.default_order_field not in fields:
            fields.append(self.default_order_field)
        return fields

**Comment by jrief** [comment]
Well spotted!
I usually do that anyway, just missed here.
