### ISSUE TITLE
Signal for Model is not Triggered when Item is Dragged

### ISSUE THREAD

**Issue by selected-pixel-jameson** [jrief/django-admin-sortable2#347]
Hello,

I have a model setup to use the SortableAdminMixin. When a user drags an item in the admin list up or down I want to trigger other actions. 

I was doing this by using Signals like so:

@receiver(post_save, sender=CoverType)
def cover_type_updated(sender, instance, **kwargs):
    ......

class CoverTypeAdmin(SortableAdminMixin, admin.ModelAdmin):
     ......

But for some reason this doesn't seem to be triggered anymore. Am I missing something? Maybe this never worked, but I thought it did.

**Comment by jrief** [comment]
Please follow these instructions when reporting bug:
https://django-admin-sortable2.readthedocs.io/en/latest/contributing.html#reporting-bugs

**Comment by selected-pixel-jameson** [comment]
This is not necessarily a bug. I'm just asking if this is a feature of the library. I've read through most of the documentation and it doesn't say anything about being able to hook into the save process of a model when a model is dragged and dropped. I thought this used to work so I was just asking why.

**Comment by jrief** [comment]
You can do this by overriding method `update_order` in you `ModelAdmin` class. There you have a hook which is called every time the user moves an item inside the list view.
