### ISSUE TITLE
missing template(s) for Django 4.2

### ISSUE THREAD

**Issue by Wekhrlin** [jrief/django-admin-sortable2#348]
With the new version 4.2 of Django, some templates (in my case: stacked-django-4.2.html but this should also apply to tabular-django-4.2.html) are missing. The templates for 4.1 can be used and should be included in a newer version of the plugin. As a hotfix, one could just copy/rename the files in python3.9/site-packages/adminsortable2/templates/adminsortable2/edit_inline/

**Comment by daweedm** [comment]
#349

**Comment by jrief** [comment]
Version 2.1.6 has been released.
