### ISSUE TITLE
Make *only* inlines sortable and not the base model admin?!?

### ISSUE THREAD

**Issue by jedie** [jrief/django-admin-sortable2#363]
Since version 2 it's needed to add SortableAdminMixin to the "main" ModelAdmin class and not only to InlineModelAdmin...

This will always add sort `_reorder_` to `list_display` even it the main ModelAdmin isn't sortable!

Current work-a-round: Remove the added `_reorder_` in own `get_list_display()`, but this is boring.

Did i miss something?!?

**Comment by NullPrice** [comment]
This still appears to be an issue in the latest version.

**Comment by jrief** [comment]
check `testapp/admin.py:68`: You must add `SortableAdminBase` to your `ModelAdmin`.
