### ISSUE TITLE
Unable to see sort column (no pads) v2.1.9

### ISSUE THREAD

**Issue by halessi** [jrief/django-admin-sortable2#372]
Django 4.1

Minimal replication: 

Models.py:
```

class testLesson(models.Model):
    title = models.CharField(max_length=200)
    
    def __str__(self):
        return self.title
        

class testCell(models.Model):
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False)
    lesson = models.ForeignKey(testLesson, on_delete=models.CASCADE)
    content = models.TextField()
    
    class Meta:
        ordering = ['my_order']
        
    def __str__(self):
        return self.content[:50]   
```

Admin.py: 

```
from .models import testCell, testLesson
from adminsortable2.admin import SortableTabularInline, SortableAdminBase

class testCellInline(SortableTabularInline):
    model = testCell
    extra = 1

@admin.register(testLesson)
class testLessonAdmin(SortableAdminBase, admin.ModelAdmin):
    inlines = [testCellInline]
```

View in admin portal: 

![image](https://github.com/jrief/django-admin-sortable2/assets/34874946/1d504d6d-2be1-4ea3-991e-61e7650b62e4)

**Comment by halessi** [comment]
Note that I can un-hide the "my_order" field in the DOM? But there are still no pads. 

![image](https://github.com/jrief/django-admin-sortable2/assets/34874946/d6d6d34e-b598-4f60-9dc8-bb4e25cb5043)

**Comment by lsmith77** [comment]
seems like I am encountering the same issue on Django 4.2 https://github.com/jrief/django-admin-sortable2/issues/374

**Comment by CiaranSanders** [comment]
also running into the same issue here on Django 4.0 and django-admin-sortable2 v2.1.10

Following the docs I am able to get the List View sortable functionality working. But all attempts at getting inlines to be sortable are failing exactly as you both have described.

**Comment by jrief** [comment]
Sorry I don't understand what you mean.
