### ISSUE TITLE
Why not adapt for django 3.2?

### ISSUE THREAD

**Issue by engAmirEng** [jrief/django-admin-sortable2#381]
Is there any api that you are using that is not easy to adapt with django 3.2?
dj 3.2 is the major release and you should support it please!!

**Comment by jrief** [comment]
since I don't use django-angular myself anymore, I don't have any incentive.
You have two options: Either do it yourself, or pay me to do it for you.

**Comment by trawick** [comment]
@engAmirEng Hopefully I understood your question :)  django-admin-sortable2 version 1.0.4 works with Django 3.2.

**Comment by jrief** [comment]
@engAmirEng Sorry, my previous answer was for the wrong repository.

In Django-4, the API for rendering forms changed. I therefore created a new version incompatible with the previous one, hence 2+.

**Comment by jrief** [comment]
@engAmirEng Django-3.2 reaches EOL on April 1st 2024. In your own interest, you should migrate to Django-4+ as soon as possible.

**Comment by jrief** [comment]
Porting the new features of django-admin-sortable2 to a version running with Django<4 won't happen. You then have to stay with 1.0.4.
