### ISSUE TITLE
Support for Django 5

### ISSUE THREAD

**Issue by huynguyen-ff** [jrief/django-admin-sortable2#387]
Hi, thanks for the great package. Currently django has release the 5.x.x. version but it looks like our package haven't supported it yet because our template is just for 4.0 -> 4.2. Do you plan to support 5+ version in future?

**Comment by jrief** [comment]
yes. Unfortunately some unit tests fail when testing against Django-5, and I had no time yet to fix them. Be assured, I'm working on it.

**Comment by enoquesantos** [comment]
Hi

django-admin-sortable2 it's a very useful extension but I'm getting this error on Django 5:

```
TemplateDoesNotExist
django.template.exceptions.TemplateDoesNotExist: adminsortable2/edit_inline/stacked-django-5.0.html
```

Django 5 support will be very appreciated! :)

Thank you.

**Comment by jrief** [comment]
Version [2.2](https://pypi.org/project/django-admin-sortable2/2.2/) has official support for Django-5.
