### ISSUE TITLE
adminsortable2.js file is missing 

### ISSUE THREAD

**Issue by CrimeMasterGogo0814** [jrief/django-admin-sortable2#393]
adminsortable2.js file is missing in version 2.2 causing order to not work in admin

**Comment by robertvy** [comment]
Same here. Django is looking for the normal js, but only the minified one is collected.

**Comment by magoreal4** [comment]
I have the same problem.

**Comment by jrief** [comment]
... ups

Right! With `DEBUG = True` the unminimized file is loaded, otherwise the minimized one.

Fixed in 2.2.1

**Comment by parkan** [comment]
for those looking for a solution to this, you need django>=4.2 and django-admin-sortable>=2.2.1 as it's fixed in this commit https://github.com/jrief/django-admin-sortable2/commit/5ea4352958ad85b98763f3ea889f8e91953b1c0d
