### ISSUE TITLE
Selected ordering is not preserved when using "Save as new"

### ISSUE THREAD

**Issue by ldeluigi** [jrief/django-admin-sortable2#402]
After some debugging I found the source of the issue:
https://github.com/jrief/django-admin-sortable2/blob/3cbfa1a0a08078a6ec4dfc0e7ec67bfb9d02aeb0/adminsortable2/admin.py#L489-L491

Basically when saving as new the order passed with the form submission gets discarded because its value is greater than or equal to 0, as per `order_field_value >= 0`.

Instead, when saving as new after a customization of the field ordering, the selected order should be honored.

**Comment by jrief** [comment]
Thanks @ldeluigi for this pull request. Please be patient, I need some time to test this. I am just wondering, if this might cause some regressions, otherwise that comparison wouldn't be the way it is in the first place.

**Comment by ldeluigi** [comment]
I have no idea, I tested with the testapp in this repository!

**Comment by ldeluigi** [comment]
PS. The value is not negative, I just needed the if condition to not pass if it is 0 or greater

**Comment by ldeluigi** [comment]
The negative check is in case someone messes with the template by overriding in some strange way that would cause negative values to appear

**Comment by ldeluigi** [comment]
In other words, when saving as new, the **order_field_value** already contains the desired value and should not be overwritten, that's why I inverted the if condition

**Comment by jrief** [comment]
Let's see if anyone complains about this after upgrading to version 2.2.4.

**Comment by zlorf** [comment]
Hi!
I just stumbled upon a problem that when adding a new object with new inlines, every inline model is saved with order = 0 (where 0 is the default value for the field, as suggested by the docs).

I think the condition should be changed to `if order_field_value is None or order_field_value <= 0:`. This way ordering is preserved if specified (when > 0), and auto-ordered when new objects are created.

**Comment by ldeluigi** [comment]
It would break when you update a list I think

**Comment by ldeluigi** [comment]
The ideal solution would be to change the javascript so that new inlines have order field equal to a negative number, this way they can be distinguished from the first in order on update

**Comment by zlorf** [comment]
1. I've tested it in my new project with the change I mentioned and it works correctly for both new and updated lists. However, I haven't tried "save as new" yet, just adding a new model with inlines and editing an existing one.
2. IIUC, for editing a list order, JavaScript sets the numbers for order and it starts with 1. So there is a clear distinction between new elements (0) and edits (>0).

**Comment by zlorf** [comment]
I've just tried "save as new" and the order is preserved as it should.

I'm sending a PR in that case.

**Comment by zlorf** [comment]
https://github.com/jrief/django-admin-sortable2/pull/416 sent.

**Comment by stefanofusai** [comment]
Also experiencing the same issue, looking forward to the PR being merged!
