### ISSUE TITLE
Compatibility issue with Django 5.1

### ISSUE THREAD

**Issue by aminvsf** [jrief/django-admin-sortable2#405]
After upgrading to Django 5.1, a template does not exist error has occurred for my admin orderable inlines:

![image](https://github.com/user-attachments/assets/3387eae5-013c-4185-93ca-ef0909b4e985)

**Comment by ldeluigi** [comment]
same for `django.template.exceptions.TemplateDoesNotExist: adminsortable2/edit_inline/tabular-django-5.1.html`

**Comment by fsbraun** [comment]
@ldeluigi @aminvsf Can you give #406 a test run?

**Comment by ldeluigi** [comment]
Could we implement a fallback for future django versions that simply uses the latest available template?

**Comment by ldeluigi** [comment]
@jrief sorry for the ping, but could you release a new version for the 5.1 fix?
