### ISSUE TITLE
order starts with -1

### ISSUE THREAD

**Issue by sigma-plus** [jrief/django-admin-sortable2#412]
when drag with `SortableAdminMixin` in Admin List , the post request is "updatedItems:[["9", -1], ["8", 0]]"  . The order field starts with "-1", which is invalid with PositiveIntegerField.

Django Version: 5.1.2

**Comment by jrief** [comment]
could you please give me a receipt on how to reproduce this using the provided `testapp`.

**Comment by sigma-plus** [comment]
I  use the demo in your docs. when I  add books with commands as below:
![image](https://github.com/user-attachments/assets/07fab132-f69a-49c2-9f20-13ad487ce3bf)

the Admin List can not reorder, because the new order is -1, which cause `400 Bad Request`

but when I use admin form page to add books , it works.

**Comment by jrief** [comment]
If you create the objects yourself, you then of course have to provide the initial data yourself.

**Comment by sigma-plus** [comment]
> If you create the objects yourself, you then of course have to provide the initial data yourself.

thanks for your reply. but it's wired when you cannot reorder the  admin list items when these items has equal order value `0`.
