### ISSUE TITLE
Sorting does not work when ordering is descending `(-order,)`

### ISSUE THREAD

**Issue by tino** [jrief/django-admin-sortable2#42]
I want new items to appear up top, so I reverted the sort order on the model:

```
class Meta:
        ordering = ('-order',)
```

The order shown in the admin is correct, but all strange things happen when I sort. I can never get an item in the right place, they jump back or end up higher or lower.

**Comment by jrief** [comment]
Yes, I can confirm this.
I must dig more into this issue, there is no trivial solution.

**Comment by jrief** [comment]
Please retest in your environment. If this fixes your issue, please confirm. I then will release a new version.

**Comment by tino** [comment]
Hi, it's better (consistent), but not correct:

When ordering is *descending* on `model.Meta`:

- n up = n+1 up
- n down = n-1 down
- moving an item to the top gives it `order = 0`, therefore moving it to last

It does not matter wether I reverse the sort by clicking on the column (eg. appending `?o=1` to the url) or setting `admin.ModelAdmin.ordering` *ascending*, behaviour stays the same (visually).

**Comment by jrief** [comment]
Please try to reorder with ``./manage reorder yourmodel``. Then check again. If for some reason, the order field reached 0, then this can happen.
In my setup however, I'm unable to move an item to the first place. Instead, I have to move the first item down. This, FMPOV is caused by a problem in ``jquery.ui.sortable``.

**Comment by tino** [comment]
Ah, check, that is working.

About the top item: With descending, I can only put an item to the top by putting it second, and then moving the top item 2 or more down. Otherwise it doesn't work. With order ascending, moving it one down is enough.

**Comment by tino** [comment]
How would we get this working? What is going wrong in `jQuery.ui.sortable` that creates this error?
