### ISSUE TITLE
adminsortable package name still used in documentation

### ISSUE THREAD

**Issue by chuckSMASH** [jrief/django-admin-sortable2#53]
The project documentation on readthedocs doesn't yet reflect the new package name in several places. Opening a bug for this since it's likely to trip up potential users trying to follow the docs. Here are the occurrences I found:

http://django-admin-sortable2.readthedocs.org/en/latest/installation.html#configuration

```python
INSTALLED_APPS = (
    ...
    'adminsortable',
    ...
)
```

http://django-admin-sortable2.readthedocs.org/en/latest/usage.html#integrate-into-a-list-view
```python
from adminsortable.admin import SortableAdminMixin
```

http://django-admin-sortable2.readthedocs.org/en/latest/usage.html#integrate-into-a-detail-view
```python
from adminsortable.admin import SortableInlineAdminMixin
```

**Comment by jrief** [comment]
Thanks for reporting. I had to manually trigger "readthedocs".
