### ISSUE TITLE
Html minifier makes the reorder handle disappear

### ISSUE THREAD

**Issue by dinoperovic** [jrief/django-admin-sortable2#54]
When using a html minifier like [django-htmlmin](https://github.com/cobrateam/django-htmlmin) the reorder handle disappears because `&nbsp;` is removed from drag div.

Without htmlmin:
`<td class="field-_reorder"><div class="drag" order="1">&nbsp;</div></td>`

With htmlmin:
`<td class="field-_reorder"><div class="drag" order="1"></div></td>`

Had to exclude admin from the minifier:
`EXCLUDE_FROM_MINIFYING = (r'^admin/', )`

Just wanted to point this out.

**Comment by jrief** [comment]
Well, wouldn't you say, that if someone adds ``&nbsp;`` he emphasizes a non-breaking-space, one which absolutely must be added.
Therefore in my humble opinion, this has to be fixed in the minimizer – or can you give me some other reasonable reason, why this has to be so?

**Comment by dinoperovic** [comment]
I agree, just wanted to point it out in case someone stumbles on this issue.
