### ISSUE TITLE
Tabular inline entire row draggable

### ISSUE THREAD

**Issue by nicholasserra** [jrief/django-admin-sortable2#56]
Just need some confirmation on whether this is a bug. On tabular inlines, instead of just the "sort" area activating the drag and drop, then entire row activates it. I can click anywhere in the tabular row and drag the row around. 

From the docs it seems like the desired behavior is that only the spot to the very left in the 'sort' column should activate drag.

Looking to dive in and fix this, but not sure if it's intended behavior. Thanks!

**Comment by jrief** [comment]
Yes for Tabular Inlines the whole line can be dragged. For normal list view you have to click onto the sensitive area.

**Comment by nicholasserra** [comment]
Gotcha. The docs seemed contradictory:

`The interface for a sortable tabular inline view adds a sensitive area to each draggable row. These rows then can be moved up and down.`

If the whole row activates the drag, then it doesn't seem like the sort area even needs to be displayed. Only reason I'm bringing this up is that, for complex inlines, having the entire row activate drag is kind of jarring. 

I implemented a fix to only have the handle be on the sortable column, but I don't want to break backwards compatibility. Trying to think of a way to accomplish this via a django setting that can be toggled.

**Comment by jrief** [comment]
Well if it is a kind of sensible area, then for the user experience, we don't break anything.

I also believe that users are used to these kind of "rough surface structures", so if you add this to Tabular Inline, I'd appreciate it.
