### ISSUE TITLE
when adding a new inline, it appears at first position after save

### ISSUE THREAD

**Issue by benzkji** [jrief/django-admin-sortable2#66]
when adding a new inline, it appears at first position after save, although when adding, it as added at last position. one must not order before save (common use case...) to reproduce this.

when addding `default=999` in the order field definition, it works as expected. I'm not sure how it should behave, as the docs say `default=0`...?

**Comment by cstrap** [comment]
Maybe the bug sounds like #63 that happens to me.

Could you try to debug the ```adminsortable2/admin.py``` and see if the ```if getattr(obj, self.default_order_field, None) is None:``` (row 278) is ```True```?
This statement, as you can see on code, evaluate ```max_order``` that is the value used to put the new inserted item on the last position.

I suspect that ```self.default_order_field``` is not ```None``` and his value is a number, 0 or maybe the default model value.

**Comment by benzkji** [comment]
I could not test yet, but I have already seen that it submits "0" for the added inline's order field...will check your suggestions soon.

**Comment by therg** [comment]
That is the issue. Just remove the default and use `blank=True` and `null=True` and it works by appending as expected. The docs are incorrect when they say `default=0` is required.

**Comment by cstrap** [comment]
I update the description on PR #63 with a reference to this issue.
Thanks for contributing @therg

**Comment by benzkji** [comment]
after a quick check, I can confirm that `blank=True` and `null=True` work perfect. THX!
