### ISSUE TITLE
Please: use an iterator in the "reorder" command

### ISSUE THREAD

**Issue by tecnosegugio** [jrief/django-admin-sortable2#67]
Executing a "reorder" on a table with hundred of thousands records require a lot of memory and time.

The problem come from the loop:
for obj in Model.objects.all():
which usually load in memory the whole resultset.

Try instead something like:
for obj in Model.objects.iterator():

**Comment by jrief** [comment]
I presume, you intended the iteration in the management command.

**Comment by tecnosegugio** [comment]
Exactly.

Thank you.

**Comment by jrief** [comment]
Just for curiosity (since I never ran into that problem myself), how many items do you have in that database table?

Is this is on public website - URL?

**Comment by tecnosegugio** [comment]
406000 items and they are growing every day. ;-)

Sorry, they are not on a public site.

Ah! Almost forgot to say that even DEBUG setting must be setted to False
otherwise Django will eat all memory and then crash.

-- 
-=) Pierpaolo AKA il Tecnosegugio da mobile (=-

**Comment by jrief** [comment]
But almost half a million of items, sorting still must be very hard! Currently you can move them to the next page and to the last page. I presume that with such a dataset it would be great to move items to a specific page. How do you handle that?
