### ISSUE TITLE
Dragging first to last in list doesn't work

### ISSUE THREAD

**Issue by mbox** [jrief/django-admin-sortable2#70]
Steps to reproduce:
- Using SortableAdminMixin (sort on the change_list view)
- Create 3 items in the admin
- Try to drag the top item to the second position - works fine
- Try to drag the top item to the *end* of the list - it drops as the _second_ item not the last

Seen with 0.5.1, Django 1.6.11, Safari on OS X 10.10.4

**Comment by kelly-apollo** [comment]
+1

**Comment by jrief** [comment]
OK, this seems to be related to the jQuery plugin used to handle the dragging.

**Comment by max-pfeiffer** [comment]
+1 

Using Firefox 42.0

**Comment by jrief** [comment]
I just retested in my environment, everything works fine.
My environment includes jQuery JavaScript Library v1.9.1, and yours?

**Comment by max-pfeiffer** [comment]
Hi Jacob, my setup:

Django==1.8.6
django-admin-sortable2==0.6.0

Not sure what jQuery version that django version uses.
This is what is loaded on that Admin Page which uses your app:
```
<script src="/static/admin/js/core.js" type="text/javascript">
<script src="/static/admin/js/admin/RelatedObjectLookups.js" type="text/javascript">
<script src="/static/admin/js/jquery.js" type="text/javascript">
<script src="/static/admin/js/jquery.init.js" type="text/javascript">
<script src="/static/admin/js/actions.js" type="text/javascript">
<script src="/static/admin/js/calendar.js" type="text/javascript">
<script src="/static/admin/js/admin/DateTimeShortcuts.js" type="text/javascript">
<script src="/static/admin/js/inlines.js" type="text/javascript">
<script src="/static/adminsortable2/js/plugins/admincompat.js" type="text/javascript">
<script src="/static/adminsortable2/js/libs/jquery.ui.core-1.11.4.js" type="text/javascript">
<script src="/static/adminsortable2/js/libs/jquery.ui.widget-1.11.4.js" type="text/javascript">
<script src="/static/adminsortable2/js/libs/jquery.ui.mouse-1.11.4.js" type="text/javascript">
<script src="/static/adminsortable2/js/libs/jquery.ui.sortable-1.11.4.js" type="text/javascript">
<script src="/static/adminsortable2/js/inline-sortable.js" type="text/javascript">
```

**Comment by jrief** [comment]
> Not sure what jQuery version that django version uses.

well, then open the file.

**Comment by max-pfeiffer** [comment]
;-)  jQuery JavaScript Library v1.11.2

**Comment by jrief** [comment]
I run admin-sortable2 side by side with django-cms. The CMS replaces jQuery by a newer version. Can you please try to do so as well. Simply add a newer version somehow higher in the static search file path.

**Comment by max-pfeiffer** [comment]
My version v1.11.2 is newer than your v1.9.1 version or do I get something wrong here? I just checked the [version history](https://en.wikipedia.org/wiki/JQuery#Release_history) to make sure. 

So what do you want me to do? Use the jQuery v2.1?

**Comment by jrief** [comment]
I upgraded to Django-1.8.7 and do not experience this problem in the list view.
However the StackedInline doesn't work properly. I can move Items, but after saving, the order is not updated.

**Comment by max-pfeiffer** [comment]
I just upgraded my packages:

Django==1.8.7
django-admin-sortable2==0.6.2

Sorting and saving works fine on my side, exept this issue.

**Comment by jrief** [comment]
I can not reproduce this with version 0.6.4
