### ISSUE TITLE
Management commant reorder & ordering = ('-position',)

### ISSUE THREAD

**Issue by wullerot** [jrief/django-admin-sortable2#76]
Hello, 
think i found a little bug in the management command reorder. 
if i have a negative ordering ( ordering=('-position',) ) the reorder command fails silently

this could be fixed:
in management.command.reorder line 24
```python
orderfield = Model._meta.ordering[0]
```
should be replaced with
```python
orderfield = Model._meta.ordering[0]
if orderfield[0] == '-':
    orderfield = orderfield[1:]
```

**Comment by jrief** [comment]
rare use-case, but valid. Thanks!
