### ISSUE TITLE
Admin action Move to other page with ordering = ('-position',)

### ISSUE THREAD

**Issue by wullerot** [jrief/django-admin-sortable2#77]
Somewhat related to [#76](https://github.com/jrief/django-admin-sortable2/issues/76)
if you define "negative" ordering (ordering = ('-position',)) the admin actions which moves the selected item(s) back don't work. The "endorder" value in _bulk_move gets a completely wrong value.

**Comment by jrief** [comment]
I just tested to move an item ``-1`` pages forward, and it is moved back. The same vice versa, everything just works as expected.
