### ISSUE TITLE
Regression in #74

### ISSUE THREAD

**Issue by jrief** [jrief/django-admin-sortable2#78]
@teddybeermaniac Today I came across a nasty regression introduced by #74.
Whenever list-sortable.js is included by a detail view, the change_list.html template can't initialize the global variables sortable_current_page and sortable_total_pages. Then accessing these variables results into a Undefined exception.

Patch for this is on the way. Please recheck in your envionment.

**Comment by teddybeermaniac** [comment]
I don't know why, but the whole time I lived with an assumption that list-sortable.js would only be included in object list not on change page so I didn't even check. Sorry, my bad.

**Comment by jrief** [comment]
Since implicit global variables are evil, I introduced an objects named ``admin_sortable2`` which is member of the ``window`` object. I hope this will make things cleaner and clearer.
I hope its in your sense.
