### ISSUE TITLE
Thoughts on grappelli integration?

### ISSUE THREAD

**Issue by kennknowles** [jrief/django-admin-sortable2#8]
Hello,

I agree with the philosophy behind this rewrite. One problem is that I am using [https://github.com/sehmaschine/django-grappelli](grappelli) which seems to override important bits needed for the `SortableInlineAdminMixin`.

Do you have a thought about adding some support or else advise on how to proceed?

\- Kenn

**Comment by pitagora04** [comment]
> Nevermind! It seems that this is part of Grappelli: https://django-grappelli.readthedocs.org/en/latest/customization.html#inline-sortables

Kindly asking you to describe how did you solve it at the end ?
I'm using both `django-grappelli` and `django-admin-sortable2` and Inlines are falling apart when trying to use sort...
![image](https://user-images.githubusercontent.com/10758715/156430520-7e113e9d-4cbd-4a8b-ba6e-4ac2aee0e875.png)

**Comment by pitagora04** [comment]
> > Nevermind! It seems that this is part of Grappelli: https://django-grappelli.readthedocs.org/en/latest/customization.html#inline-sortables
> 
> Kindly asking you to describe how did you solve it at the end ? I'm using both `django-grappelli` and `django-admin-sortable2` and Inlines are falling apart when trying to use sort... ![image](https://user-images.githubusercontent.com/10758715/156430520-7e113e9d-4cbd-4a8b-ba6e-4ac2aee0e875.png)

Solution was to use `GrappelliSortableHiddenMixin`:
```
class SectionInline(GrappelliSortableHiddenMixin, admin.StackedInline):
```
