### ISSUE TITLE
SortableInlineAdminMixin interferes with InlineModelAdmin.show_change_link

### ISSUE THREAD

**Issue by max-pfeiffer** [jrief/django-admin-sortable2#81]
When using the SortableInlineAdminMixin class the [new Django 1.8 feature InlineModelAdmin.show_change_link](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#inlinemodeladmin-objects) does't work any more.

To reproduce:
1. Add show_change_link=True to your inline model.
2. Change Link appears ontop of inline
3. Add the SortableInlineAdminMixin to your Inline class
4. Change link disappears

Using:
Django==1.8.7
django-admin-sortable2==0.6.2

**Comment by arthexis** [comment]
I am having this issue as well.

**Comment by jrief** [comment]
@max-pfeiffer @arthexis 
I just tested this. What would I have to change in the example code to get this link working. My assumption is, that the event handler for dragging inhibits to click on the link, so probably I must declare something else as the draggable area.
