### ISSUE TITLE
Adding fields to InlineModelAdmin classes results in a KeyError

### ISSUE THREAD

**Issue by max-pfeiffer** [jrief/django-admin-sortable2#83]
When adding field entries to BaseModelAdmin.fields in one of the InlineModelAdmin classes django-admin-sortable throws a KeyError. I didn't test it with the ModelAdmin class.

This is probably due to field that holds the position value, which is marked as hidden. But this is not good, because sometimes you need to specify fields.

Also it would be good if you can display the position value in an inline. This makes sense when you have a lot of inlines and you want to place an inline on a certain position.

Using:
Django==1.8.7
django-admin-sortable2==0.6.2

![screen shot 2015-12-16 at 10 46 12](https://cloud.githubusercontent.com/assets/13573675/11837619/5a0c74bc-a3e2-11e5-8020-635ab3d6ebdd.png)

**Comment by tezro** [comment]
Got the same error now. Django 1.8.11, django-admin-sortable2==0.6.3.

**Comment by tezro** [comment]
Model:
```
class ProjectImage(models.Model):
    project = models.ForeignKey(Project)
    order = models.PositiveIntegerField(default=0, editable=False, db_index=True)

    class Meta(object):
        ordering = ('order',)
```
Admin:
```
from adminsortable2.admin import SortableAdminMixin, SortableInlineAdminMixin
from .models import Project, ProjectImage

class ProjectImageInline(SortableInlineAdminMixin, admin.TabularInline):
    model = ProjectImage

class ProjectAdmin(TranslatableAdmin):
    inlines = [ProjectImageInline]
admin.site.register(Project, ProjectAdmin)
```

This is frustrating... Works perfectly on other projects.

**Comment by jrief** [comment]
In my projects I've used (similar to yours) this pattern:

```
class ProjectImageInline(SortableInlineAdminMixin, admin.StackedInline):
    model = ProjectImage
    ordering = ('order',)
```

and it works perfectly.

**Comment by tezro** [comment]
I've just created a new model like this with a different name. Same error.

It can't be because of the SQLite?

**Comment by tezro** [comment]
```
editable=False
```
That was my problem. Field name gets removed from the field list if set to editable .

**Comment by jrief** [comment]
No, I tested it with SQLite and MySQL.

**Comment by jrief** [comment]
Oh, thanks for finding out yourself. Could you please a a line or two to the docs, so that other don't step into the same trap.
