### ISSUE TITLE
Javascript Error: sortable_current_page is not defined

### ISSUE THREAD

**Issue by chadsaun** [jrief/django-admin-sortable2#87]
I'm getting this JS error when I'm viewing a specific Artwork Category and viewing the tabular inline of all the artwork.  

<img width="886" alt="screen shot 2016-01-13 at 10 55 51 am" src="https://cloud.githubusercontent.com/assets/381024/12303483/d7ad9db8-b9e7-11e5-9a1c-7a1a39f7073d.png">

Here is my setup:

```
class ArtworkAdminInline(SortableInlineAdminMixin, admin.TabularInline):
    model = Artwork
    image_thumb = image_file('obj.image', short_description='Thumbnail')
    readonly_fields = ('image_thumb',)

class ArtworkCategoryAdmin(SortableAdminMixin, admin.ModelAdmin):
    inlines = [ArtworkAdminInline]
```

I'm not sure why it's including `list-sortable.js` on this page since all it needs is just `inline-sortable.js`.  If I restart my localhost server this will work fine and only include `inline-sortable`.  But if I browse back to the list of Artwork Categories and then go into a different Artwork Category, then it includes both of those js files and I get the error.

I'm using Django 1.8 and django-admin-sortable2 0.6.0

**Comment by jrief** [comment]
Please upgrade to version 0.6.2.
The changelog states: Fixed regression from 0.6.0: Multiple sortable inlines are now possible again.
If that helps, please close.

**Comment by chadsaun** [comment]
Yep, that seems to have fixed it.  Thank you

**Comment by linda-urech** [comment]
I'm getting the same same error (but without using inlines). It happens when I try to edit a sortable model in the admin of django-cms. If I restart my localhost server, the first time it works fine, but if I move back to the admin overview and click the sortable model again to edit it, I'm getting the javascript error `ReferenceError: sortable_current_page is not defined`
This is my admin (if that helps):
```
class PortfolioTeaserAdmin(SortableAdminMixin, TabbedTranslationAdmin):
    list_display = ['project_name', 'heading', 'author', 'link_to_page']
    readonly_fields = ['link_to_page']

    def link_to_page(self, obj):
        html = '<a href="{0}">Show Connected Page</a>'
        if obj.teaser_extension.first() != None:
            page = obj.teaser_extension.first().get_page()
            url = page.get_draft_url()
            return html.format(url)
        else:
            return None

    link_to_page.allow_tags = True
    link_to_page.short_description = "Link"
```
I'm using:
admin-sortable2 v. 0.6.2
django v.1.8.4
django-cms v.3.2
