### ISSUE TITLE
a bug when ModelAdmin.exclude is a tuple

### ISSUE THREAD

**Issue by leench** [jrief/django-admin-sortable2#92]
adminsortable2/admin.py", line 60, in __init__
    self.exclude = [self.default_order_field] + self.exclude
TypeError: can only concatenate list (not "tuple") to list

**Comment by leench** [comment]
And I found django-admin-sortable2 cannot work with django-reversion together, any ideas?

**Comment by jrief** [comment]
Please retest, and if everything is OK, I'll push a new version

**Comment by leench** [comment]
That is fixed. thanks

**Comment by leench** [comment]
sorry there is another problem. wait 1 min

**Comment by andreyshipilov** [comment]
@leench Hey man. Did you manage to make it work with django reversion? I think I have the same problem now. Cheers.

**Comment by andreyshipilov** [comment]
Guys, any idea why there's no reversion related “recover deleted” in admin? I can access the url where I can recover deleted objects, but I don't see the link to this page on the form list.

Please help.
