### ISSUE TITLE
Installing with Docker pip3 cause UnicodeDecodeError

### ISSUE THREAD

**Issue by trung-kitchenstories** [jrief/django-admin-sortable2#95]
When I try to install **django-admin-sortable2==0.6.2** in Docker with pip3 this error occurs.

Error:

    Collecting django-admin-sortable2==0.6.2 (from -r /tmp/requirements.txt (line 11))
      Downloading django-admin-sortable2-0.6.2.tar.gz (47kB)
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-7uiq52zk/django-admin-sortable2/setup.py", line 33, in <module>
            long_description=convert('README.md', 'rst'),
          File "/tmp/pip-build-7uiq52zk/django-admin-sortable2/setup.py", line 11, in convert
            return fd.read()
          File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
            return codecs.ascii_decode(input, self.errors)[0]
        UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 876: ordinal not in range(128)

The Fix works with **codecs** instead of **io**
Fix: 

    try:
        from pypandoc import convert
    except ImportError:
        import codecs
        def convert(filename, fmt):
            with codecs.open(filename, 'r', 'utf-8') as fd:
                return fd.read()

**Comment by jrief** [comment]
Thanks for reporting.
Just released 0.6.3 which fixes this.
