### ISSUE TITLE
js error in admin (list-sortable.js)

### ISSUE THREAD

**Issue by metaforx** [jrief/django-admin-sortable2#98]
Uncaught TypeError: jQuery.getQueryParams is not a function

It might be that jquery is not yet ready at the point where list-sortable functions are called. 

I tried removing inlines, admin-style, but the issue stays. Any idea what this could be? I am running 0.6.3 and also had this issue with 0.6.2

Thanks for any help.

**Comment by jrief** [comment]
check that ``jquery.js`` is loaded somewhere. This normally is done by the Django admin itself. Maybe it was overridden somewhere.

**Comment by metaforx** [comment]
Hi jrief

It's loaded according to the page headers:

<script type="text/javascript" src="/static/admin/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.min.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/plugins/admincompat.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/libs/jquery.ui.core-1.11.4.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/libs/jquery.ui.widget-1.11.4.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/libs/jquery.ui.mouse-1.11.4.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/libs/jquery.ui.sortable-1.11.4.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/list-sortable.js"></script>

Adminsortable is working in django admin model overview but not in the model entry admin (where it's not used). I do not use it for inline sortable, just to sort entries in the overview. Basically it breaks some other JS-Libraries. Any ideas why?

**Comment by domenikjones** [comment]
Hey metamorf ;)
Did you find a solution for this issue? We are facing the same error on Django 1.9.x.

**Comment by fredd4** [comment]
@domenikjones 
I had the same problem. I found out, that django filer loaded secodn time jquery, but own file, below in the code. Because of it, the function $ was overwritten:
`<script src="/static/filer/js/libs/jquery.min.js"></script>
`
My solution? Hack in main urls.py file (as I did not find method without patching):
`    url(r'^/static/filer/js/libs/jquery.min.js', lambda r:HttpResponse('')),
`

**Comment by jtavarez** [comment]
FYI, upgrading django-filer to the latest version (1.2.0) solves this for me, I had the same issue.

**Comment by jrief** [comment]
@jtavarez thanks for finding out.
@fredd4 @metaforx Can you please a line to the docs explaining your fix. This will help others.

**Comment by domenikjones** [comment]
@fredd4 
Thanks for the tipp. I recommend @jtavarez solution.

@jtavarez 
Thanks. Update to django-filer 1.2.0 solved the problem. No more jQuery errors on SortableAdminMixin on detail page of a model.

**Comment by andreyshipilov** [comment]
I got the same error. Not using `django-filer`. I'm using `django-ckeditor` and on models that have a RichTextField as well as sortable inlines, the error is still thrown in the console:
```
inline-sortable.js:8 Uncaught TypeError: tabular_inlines.sortable is not a function
```

**Comment by sinchuk140995** [comment]
I installed **django-ckeditor==5.3.0** and **django-admin-sortable2==0.6.11**. Error "inline-sortable.js:8 Uncaught TypeError: tabular_inlines.sortable is not a function" was fixed. Before I have had ckeditor==5.2.1 and it was causing the error.

**Comment by jrief** [comment]
this seems as if one jQuery library is overriding another one.
Try to remove django-ckeditor, and if that works, try to change the order in INSTALLED_APPS.
This is just a hint.

You can be sure, that by itself, admin-sortabe2 works pretty well.
